# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qANgP5AvRQCH_Q-CGImtybDBJh3yehui
"""

# x values varies from 1 to 10000

sim_len=10000
i=1
Exp_Val=0

#simulation for first 10000 values of x

for i in range(sim_len):
  #Exp_Val=summation of probability*i
  Exp_Val+=((2/3)*(1/3)**(i-1))*i
  i+=1
print("The Expectation vamue by simulation is :",Exp_Val)
print("The expectation value by theory is :",3/2)